/*

Siesta 4.2.2
Copyright(c) 2009-2016 Bryntum AB
http://bryntum.com/contact
http://bryntum.com/products/siesta/license

*/
Class('Ariadne.ExtJSDomQueryFinder.Identifier.AttributeValue', {
    
    isa         : Ariadne.DomQueryFinder.Identifier.AttributeValue,
    
    does        : Ariadne.ExtJSDomQueryFinder.Role.ExtJSHelper,
    
    has         : {
        // an array of attribute names, which can be used for matching
        attributes                  : function () {
            return [
                'data-ref',
                'aria-label'
            ]
        }
    },
    
    methods : {
        
        ignoreAttribute : function (target, attributeName) {
            var value   = target.getAttribute(attributeName)
            var cmp     = this.getComponentOfDomElement(target)
            
            if (cmp && this.valueIsAutoGeneratedByComponent(cmp, value)) return true
            
            return this.SUPERARG(arguments)
        }
    }
});
