/*

Siesta 4.2.2
Copyright(c) 2009-2016 Bryntum AB
http://bryntum.com/contact
http://bryntum.com/products/siesta/license

*/
Class('Ariadne.ExtJSDomQueryFinder.Identifier.Id', {
    
    isa         : Ariadne.DomQueryFinder.Identifier.Id,
    
    does        : Ariadne.ExtJSDomQueryFinder.Role.ExtJSHelper,
    
    methods : {
        
        ignoreDomId : function (id, target) {
            return this.domElementHasAutoGeneratedId(target)
        }
    }
});
